description: "naiive averaging across all clients"
clients: 20
num_clusters: 2
num_rounds: 50
local_epochs: 1
dataset: 'cifar10'
model: 'cifarcnn'
aggregator: 'fedavg'
lr: 0.01
cluster_split_type: 'rotation'
initial_epochs: 1
baseline_avg_whole_network: False
