description: "pointwise k means. mnist, 2 clusters with different classes"
clients: 10
num_clusters: 2
num_rounds: 50
local_epochs: 1
train_sample_rate: 1.0
initial_epochs: 1
evaluation_sampling_rate: 1.0

task: 'mnist'
aggregator: 'fedavg'
lr: 0.01

cluster_split_type: 'selected_classes'
baseline_avg_whole_network: false

cluster: 'kmeans'
  #'validation_loss'
  #'filter_matching'

cluster_params:
  k_iter: 10
  filter_distance: 'max'

random_seed: 322