description: "filter matching 2 clusters cifar10 selected_classes"
clients: 10
num_clusters: 2
uneven_clusters: false
num_rounds: 50
local_epochs: 1
train_sample_rate: 1.0
initial_epochs: 0
evaluation_sampling_rate: 1.0
task: 'cifar100'
aggregator: 'fedavg'
lr: 0.01

cluster_split_type: 'selected_classes'
baseline_avg_whole_network: false

cluster: 'filter'
  # 'kmeans'
  #'validation_loss'
  #'filter'

cluster_params:
  k_iter: 10
  filter_distance: 'max'

random_seed: 322