description: "clustered data but network-wide averaging."
clients: 2
num_clusters: 1
num_rounds: 1 
local_epochs: 1
dataset: 'cifar10'
model: 'cifarcnn'
aggregator: 'fedavg'
lr: 0.01
cluster_split_type: 'rotation'
initial_epochs: 0
baseline_avg_whole_network: True
