description: "kmeans. cifar10, 5 clusters rotation"
clients: 15
num_clusters: 5
num_rounds: 30
local_epochs: 1
train_sample_rate: 1.0
initial_epochs: 1
evaluation_sampling_rate: 1.0

task: 'cifar10'
aggregator: 'fedavg'
lr: 0.01

cluster_split_type: 'rotation'
baseline_avg_whole_network: false

cluster: 'kmeans'
  #'validation_loss'
  #'filter_matching'

cluster_params:
  k_iter: 10
  filter_distance: 'max'

random_seed: 322