description: "pointwise kmeans clustering, MNIST, 2 clusters rotated"

clients: 20
num_clusters: 2
num_rounds: 50
local_epochs: 1
train_sample_rate: 1.0
initial_epochs: 1
evaluation_sampling_rate: 1.0

task: 'cifar10'
aggregator: 'fedavg'
lr: 0.01

cluster_split_type: 'rotation'
baseline_avg_whole_network: False

cluster: 'kmeans'
  #'validation_loss'
  #'filter_matching'

cluster_params:
  k_iter: 10
  filter_distance: 'max'